CODE_INLINE=$(HOME)/csce-1102/exercise3/inline_functions
PREPROCESSED= $(CODE_INLINE)/preprocessed
BIN= $(CODE_INLINE)/bin
ASM= $(CODE_INLINE)/assembly
HEADERS= $(CODE_INLINE)/headers
SOURCES= $(CODE_INLINE)/sources
OBJ= $(CODE_INLINE)/objects
GCC=/usr/bin/g++
DEBUG= -g
PRE_FLAG=-E
ASP_FLAG=-S
INCLUDES= -I $(CODE_INLINE)/headers
OBJ_FLAG=-c
GCC_FLAGS= -std=c++11
