WCS= $(HOME)/kareemikassab/web_client_for_students
BIN= $(WCS)/bin
HEADERS= $(WCS)/headers
SOURCES= $(WCS)/sources
OBJ= $(WCS)/objects
GCC=/usr/bin/g++
INCLUDES= -I $(WCS)/headers
OBJ_FLAG=-c
GCC_FLAGS= -std=c++11
