server: TCPServerSocket.cpp TCPSocket.cpp Connection.cpp GarbageCollector.cpp server.cpp 
	g++ --std=c++11 TCPServerSocket.cpp TCPSocket.cpp Connection.cpp GarbageCollector.cpp server.cpp -o server -std=c++11 -lpthread
clean: server
	rm -rf server
