CODE_OVERHEAD=$(HOME)/csce-1102/exercise3/function_overhead
PREPROCESSED= $(CODE_OVERHEAD)/preprocessed
BIN= $(CODE_OVERHEAD)/bin
ASM= $(CODE_OVERHEAD)/assembly
HEADERS= $(CODE_OVERHEAD)/headers
SOURCES= $(CODE_OVERHEAD)/sources
OBJ= $(CODE_OVERHEAD)/objects
GCC=/usr/bin/g++
DEBUG= -g
PRE_FLAG=-E
ASP_FLAG=-S
INCLUDES= -I $(CODE_OVERHEAD)/headers
OBJ_FLAG=-c
GCC_FLAGS= -std=c++11
