CODE_HOME=$(HOME)/csce1102_lab5/attempt1
OBJECTS=$(CODE_HOME)/objects
SOURCES=$(CODE_HOME)/sources
GCC=/usr/bin/g++
INCLUDES= -I $(CODE_HOME)/headers
GCC_FLAGS= -std=c++11
OBJECTS_FLAG= -c
DEBUG= -g
BIN=$(CODE_HOME)/bin

