CODE_STATIC=$(HOME)/csce-1102/exercise3/static_functions
PREPROCESSED= $(CODE_STATIC)/preprocessed
BIN= $(CODE_STATIC)/bin
ASM= $(CODE_STATIC)/assembly
HEADERS= $(CODE_STATIC)/headers
SOURCES= $(CODE_STATIC)/sources
OBJ= $(CODE_STATIC)/objects
GCC=/usr/bin/g++
DEBUG= -g
PRE_FLAG=-E
ASP_FLAG=-S
INCLUDES= -I $(CODE_STATIC)/headers
OBJ_FLAG=-c
GCC_FLAGS= -std=c++11
