CODE_ASSIGN=$(HOME)/csce-1102/Assignment1
PREPROCESSED= $(CODE_ASSIGN)/preprocessed
BIN= $(CODE_ASSIGN)/bin
ASM= $(CODE_ASSIGN)/assembly
HEADERS= $(CODE_ASSIGN)/headers
SOURCES= $(CODE_ASSIGN)/sources
OBJ= $(CODE_ASSIGN)/objects
GCC=/usr/bin/g++
DEBUG= -g
PRE_FLAG=-E
ASP_FLAG=-S
INCLUDES= -I $(CODE_ASSIGN)/headers
OBJ_FLAG=-c
GCC_FLAGS= -std=c++11
